# Generated by Django 5.1.1 on 2024-09-24 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudante',
            old_name='CPF',
            new_name='cpf',
        ),
    ]
